name: "checkmake action"

description: "GitHub action to lint your makefile with checkmake"

branding:
  icon: "check-circle"
  color: "yellow"

inputs:
  makefile:
    description: "Makefile path"
    required: false
    default: "./Makefile"
  debug:
    description: "enable debug mode"
    required: false
    default: "false"
  config:
    description: "configure path"
    required: false
    default: ""
  cli_output_file:
    description: "configure path"
    required: false
    default: "./checkmake_cli_output.txt"

outputs:
  cli_output_file:
    description: ""

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.makefile }}
    - ${{ inputs.debug }}
    - ${{ inputs.config }}
    - ${{ inputs.cli_output_file }}
