name: Test

on:
  push:

jobs:
  checkmake:
    runs-on: ubuntu-latest
    name: test-action
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: test:case1
        continue-on-error: true
        uses: ./
        id: checkmake_case1
        with:
          makefile: "tests/makefiles/TestCase1.Makefile"
          debug: false
      - name: Case1 Error Check
        if: ${{ steps.checkmake_case1.outcome != 'failure' }}
        run: |
          exit 1
      - name: test:case1
        continue-on-error: true
        uses: ./
        id: checkmake_case1_debug
        with:
          makefile: "tests/makefiles/TestCase1.Makefile"
          debug: true
      - name: Case1 Error Check
        if: ${{ steps.checkmake_case1_debug.outcome != 'failure' }}
        run: |
          exit 1
      - name: test:case1
        continue-on-error: true
        uses: ./
        id: checkmake_case1_config
        with:
          makefile: "tests/makefiles/TestCase1.Makefile"
          config: "tests/makefiles/config"
      - name: test:case1
        continue-on-error: true
        uses: ./
        id: checkmake_case1_config_notfound
        with:
          makefile: "tests/makefiles/TestCase1.Makefile"
          config: "tests/makefiles/configure"
      - name: Case1 Error Check
        if: ${{ steps.checkmake_case1_config_notfound != 'failure' }}
        run: |
          exit 1
      - name: test:case2
        uses: ./
        id: checkmake_case2
        with:
          makefile: "tests/makefiles/TestCase2.Makefile"
